# Generated by Django 2.1.7 on 2019-07-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20190707_1211'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='userid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.Userprofile'),
            preserve_default=False,
        ),
    ]
