# Generated by Django 2.1.7 on 2019-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_vote_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
