# Generated by Django 2.1.7 on 2019-07-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_vote_is_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='match',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vote',
            name='userid',
            field=models.CharField(max_length=10),
        ),
    ]
