# Generated by Django 2.1.7 on 2019-07-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20190713_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voterdetails',
        ),
    ]
