# Generated by Django 2.1.7 on 2019-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votes', '0006_delete_voterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='voterdetails',
            fields=[
                ('match', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('userid', models.CharField(default=0, max_length=100)),
                ('vote1', models.IntegerField(default=0)),
                ('vote2', models.IntegerField(default=0)),
                ('Is_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
