# Generated by Django 2.1.7 on 2019-07-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_voterdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterdetails',
            old_name='match',
            new_name='matchId',
        ),
        migrations.RenameField(
            model_name='voterdetails',
            old_name='userid',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voterdetails',
            old_name='vote1',
            new_name='team1vote',
        ),
        migrations.RenameField(
            model_name='voterdetails',
            old_name='vote2',
            new_name='team2vote',
        ),
    ]
