# Generated by Django 2.1.7 on 2019-07-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_auto_20190713_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voterdetails',
            new_name='voterdetail',
        ),
    ]
