# Generated by Django 2.1.7 on 2019-07-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_auto_20190713_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterdetail',
            old_name='matchId',
            new_name='match',
        ),
    ]
