# Generated by Django 2.1.7 on 2019-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20190713_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterdetail',
            name='matchId',
        ),
        migrations.AddField(
            model_name='voterdetail',
            name='matchno',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voterdetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
