# Generated by Django 2.1.7 on 2019-07-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_auto_20190713_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voterdetail',
        ),
    ]
