# Generated by Django 2.1.7 on 2019-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votes', '0013_delete_voterdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='uservotes',
            fields=[
                ('mnumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uname', models.CharField(default=0, max_length=500)),
                ('teamone', models.IntegerField(default=0)),
                ('teamtwo', models.IntegerField(default=0)),
                ('is_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
