# Generated by Django 2.1.7 on 2019-07-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0017_auto_20190717_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
