# Generated by Django 2.1.7 on 2019-07-06 08:34

import creatematch.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('matchno', models.IntegerField(max_length=1000)),
                ('matchId', models.CharField(default=creatematch.operations.GenerateOTP, max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
