# Generated by Django 2.1.7 on 2019-07-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0002_auto_20190706_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('kabbadi', 'Kabbadi'), ('football', 'FootBall')], default='Cricket', max_length=10),
        ),
    ]
