# Generated by Django 2.1.7 on 2019-07-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0003_match_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creatematch.category'),
        ),
    ]
