# Generated by Django 2.1.7 on 2019-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0007_auto_20190707_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
