# Generated by Django 2.1.7 on 2019-07-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0008_auto_20190707_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='votes',
        ),
    ]
