# Generated by Django 2.1.7 on 2019-07-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0010_match_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tot_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='vote1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='vote2',
            field=models.IntegerField(default=0),
        ),
    ]
