# Generated by Django 2.1.7 on 2019-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0012_match_col_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='voterdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=500)),
                ('userid', models.CharField(max_length=10)),
                ('vote1', models.IntegerField(default=0)),
                ('vote2', models.IntegerField(default=0)),
                ('Is_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
