# Generated by Django 2.1.7 on 2019-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0013_voterdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdetails',
            name='match',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
