# Generated by Django 2.1.7 on 2019-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0014_auto_20190713_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='match',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='userid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
