# Generated by Django 2.1.7 on 2019-07-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0015_auto_20190713_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voterdetails',
        ),
    ]
