# Generated by Django 2.1.7 on 2019-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0016_delete_voterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='uservote',
            fields=[
                ('mnumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uname', models.CharField(default=0, max_length=500)),
                ('teamone', models.IntegerField(default=0)),
                ('teamtwo', models.IntegerField(default=0)),
                ('is_voted', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
