# Generated by Django 2.1.7 on 2019-07-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0017_uservote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uservote',
        ),
    ]
