# Generated by Django 2.1.7 on 2019-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0018_delete_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='userno',
            field=models.IntegerField(default=0),
        ),
    ]
