# Generated by Django 2.1.7 on 2019-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatematch', '0019_match_userno'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='unit_value',
            field=models.IntegerField(default=0),
        ),
    ]
